# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# goreleaser v2 configuration
version: 2

before:
  hooks:
    - go mod tidy

builds:
  -
    id: "opnborg"
    binary: opnborg
    main: ./cmd/opnborg/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
      - netbsd
      - openbsd
      - windows
    goarch:
      - amd64
      - arm64
archives:
  -
    id: opnborg-binaries
    name_template: "opnborg-{{ .Os }}_{{ .Arch }}_{{ .Version }}"
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"
changelog:
  use: github
  sort: asc
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Improvements"
      regexp: '^.*?(perf|refactor|improve)(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "CI & Build"
      regexp: '^.*?(ci|build|chore)(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: "Others"
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^Bump SemVer'
nfpms:
  -
    file_name_template: "opnborg_package_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Michael Paepcke
    homepage: https://paepcke.de/opnborg
    maintainer: Michael Paepcke <git@paepcke.de>
    description: opnborg
    license: BSD 3-Clause
    formats:
      - deb
      - rpm
